# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#bibbase"
  weight = 20

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 30

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 60

[[main]]
  name = 'Talks <i class="fas fa-external-link-alt"></i>'
  url = "https://github.com/pat-s/presentations"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = 'CV <i class="fas fa-external-link-alt"></i>'
  url = "files/cv.pdf"
  weight = 80
