relativeurls: true
baseurl: 'https://pjs-web.de'
title: Patrick Schratz
copyright: '&copy; 2017 - {year} Patrick Schratz'
theme: academic
enableEmoji: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
min_version: 0.55

preserveTaxonomyNames: true
footnotereturnlinkcontents: <sup>^</sup>
disqusShortname: pjs-web-de
googleAnalytics: UA-35704082-2
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
paginate: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS

mediaTypes."application/manifest+json":
  suffixes:
    - "webmanifest"

outputFormats.WebAppManifest:
  mediaType:
    - "application/manifest+json"
  rel:
    - "manifest"

blackfriday:
  hrefTargetBlank: true
  fractions: true
  smartypants: true

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
